version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: delta_api_web
    command: /start
    volumes:
      - .:/app
    ports:
      - 8012:8000
    env_file:
      - .env/.dev
    depends_on:
      - redis

  redis:
    image: redis:6-alpine

